# dockerfile=>descreve os passos para buidar uma imagem
# docker-compose=>descrever como subir uma ou mais aplicação de uma unica vez

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    network:
      - rede_privada
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD = senha
      - MYSQL_DATABASE = meubanco
    volumes:
      - db_data:/var/lib/mysql
      -